# Generated by Django 5.2.6 on 2025-09-22 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('board', '0002_remove_jobapplication_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantskill',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='applicantskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='verified',
        ),
        migrations.AddField(
            model_name='skill',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='account.applicant'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('applicant', 'name'), name='unique_applicant_skill'),
        ),
        migrations.DeleteModel(
            name='ApplicantSkill',
        ),
    ]
