# Generated by Django 5.2.6 on 2025-09-21 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_experience_skills_remove_project_skills_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="Recruiter",
            name="headline",
        ),
    ]
