# Generated by Django 5.2.6 on 2025-09-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_certification_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='account.applicant'),
        ),
        migrations.AlterField(
            model_name='education',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='account.applicant'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='account.applicant'),
        ),
        migrations.AlterField(
            model_name='project',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='account.applicant'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='account.applicant'),
        ),
        migrations.AlterField(
            model_name='training',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='account.applicant'),
        ),
    ]
