services:
  postgres:
    image: postgres:latest
    container_name: talent-bridge-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: talent-bridge-db
    ports:
      - "5432:5432"
    volumes:
      - talent_bridge_postgres_data:/var/lib/postgresql/data
    networks:
      - talent_bridge_network

  redis:
    image: redis:latest
    container_name: talent-bridge-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - talent_bridge_network

volumes:
  talent_bridge_postgres_data:

networks:
  talent_bridge_network: