# Generated by Django 5.2.6 on 2025-09-21 14:50

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0003_remove_Recruiter_headline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "requirements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("in-person", "In-Person"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=12,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("contract", "Contract"),
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                        ],
                        max_length=12,
                    ),
                ),
                ("industry", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("company_description", models.TextField(blank=True)),
                ("company_website", models.URLField(blank=True)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="account.Recruiter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cover_letter", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="account.Applicant",
                    ),
                ),
                ("certifications", models.ManyToManyField(to="account.certification")),
                ("education", models.ManyToManyField(to="account.education")),
                ("experiences", models.ManyToManyField(to="account.experience")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="board.job",
                    ),
                ),
                ("skills", models.ManyToManyField(to="account.applicantskill")),
                ("training", models.ManyToManyField(to="account.training")),
            ],
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=[
                    "title",
                    "industry",
                    "location_type",
                    "type",
                    "salary_min",
                    "salary_max",
                ],
                name="board_job_title_faa1be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["created_at"], name="board_job_created_3534c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job", "status"], name="board_jobap_job_id_ad4c7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job", "created_at"], name="board_jobap_job_id_900dd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["applicant", "status"], name="board_jobap_applica_fc667c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["applicant", "created_at"],
                name="board_jobap_applica_fe07c8_idx",
            ),
        ),
    ]
