# Generated by Django 5.2.6 on 2025-09-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='training',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experiences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='training',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
